[package]
name = "solana-caching-web-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
solana-client = "2.2.7"
solana-sdk = "2.2.2"
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
